version: "3.8"

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: rag-chatbot-chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - ./content/chromadb:/chroma
