version: "3.8"

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: rag-chatbot-chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - ./content/chromadb:/chroma

  server:
    build:
      context: ./server
    container_name: rag-chatbot-server
    restart: unless-stopped
    environment:
      - PORT=4000
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      - chromadb
    ports:
      - "4000:4000"
